# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cocomo.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from cocomomath import CocomoMath

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 720)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_17.addLayout(self.verticalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.verticalLayout_17)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_4.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_4.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_4.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_4.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_4.addWidget(self.radioButton_9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_10 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_3.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_3.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_3.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_3.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_3.addWidget(self.radioButton_14)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_19.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setMaximum(9999999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_8.addWidget(self.spinBox)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMouseTracking(False)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.spinBox_2.setMaximum(9999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_9.addWidget(self.spinBox_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        self.spinBox_3.setMouseTracking(False)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.spinBox_3.setMaximum(4)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_10.addWidget(self.spinBox_3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_8)
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_2)
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_9)
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_13)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_6)
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_10)
        self.comboBox_14 = QtWidgets.QComboBox(Dialog)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_12.addWidget(self.label_17)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_7)
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_11)
        self.comboBox_15 = QtWidgets.QComboBox(Dialog)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_14.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.comboBox_16 = QtWidgets.QComboBox(Dialog)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.verticalLayout_15.addWidget(self.comboBox_16)
        self.comboBox_17 = QtWidgets.QComboBox(Dialog)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.verticalLayout_15.addWidget(self.comboBox_17)
        self.comboBox_18 = QtWidgets.QComboBox(Dialog)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.verticalLayout_15.addWidget(self.comboBox_18)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.buttonGrouplang = QtWidgets.QButtonGroup(Dialog)
        self.buttonGrouplang.setObjectName("buttonGrouplang")
        self.buttonGrouplang.addButton(self.radioButton_4)
        self.buttonGrouplang.addButton(self.radioButton_5)
        self.buttonGrouplang.addButton(self.radioButton_6)
        self.buttonGrouplang.addButton(self.radioButton_7)
        self.buttonGrouplang.addButton(self.radioButton_8)
        self.buttonGrouplang.addButton(self.radioButton_9)
        self.buttonGrouplang.addButton(self.radioButton_10)
        self.buttonGrouplang.addButton(self.radioButton_11)
        self.buttonGrouplang.addButton(self.radioButton_12)
        self.buttonGrouplang.addButton(self.radioButton_13)
        self.buttonGrouplang.addButton(self.radioButton_14)
        self.pushButton.setEnabled(False)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.showokmessage)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.pushButton.clicked.connect(self.calclicked)
        self.spinBox.valueChanged.connect(self.deackloc)
        self.spinBox_2.valueChanged.connect(self.deacufp)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cocomo Calculator @ HTWK Edition"))
        self.label_2.setText(_translate("Dialog", "Project Type"))
        self.label_5.setText(_translate("Dialog", "Language"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.label_6.setText(_translate("Dialog", "KLOC"))
        self.radioButton_3.setText(_translate("Dialog", "organic"))
        self.radioButton.setText(_translate("Dialog", "embedded"))
        self.radioButton_2.setText(_translate("Dialog", "semi-detached"))
        self.label.setText(_translate("Dialog", "UFP"))
        self.label_3.setText(_translate("Dialog", "RELY"))
        self.comboBox.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox.setItemText(2, _translate("Dialog", "low"))
        self.comboBox.setItemText(3, _translate("Dialog", "high"))
        self.comboBox.setItemText(4, _translate("Dialog", "very high"))
        self.label_4.setText(_translate("Dialog", "DATA"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "low"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "high"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "very high"))
        self.label_8.setText(_translate("Dialog", "CPLX"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "very high"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "ultra high"))
        self.label_9.setText(_translate("Dialog", "TIME"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "high"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "very high"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "ultra high"))
        self.label_10.setText(_translate("Dialog", "STOR"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "high"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "very high"))
        self.comboBox_8.setItemText(3, _translate("Dialog", "ultra high"))
        self.label_11.setText(_translate("Dialog", "VIRT"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_9.setItemText(1, _translate("Dialog", "low"))
        self.comboBox_9.setItemText(2, _translate("Dialog", "high"))
        self.comboBox_9.setItemText(3, _translate("Dialog", "very high"))
        self.label_12.setText(_translate("Dialog", "TURN"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_10.setItemText(1, _translate("Dialog", "low"))
        self.comboBox_10.setItemText(2, _translate("Dialog", "high"))
        self.comboBox_10.setItemText(3, _translate("Dialog", "very high"))
        self.label_13.setText(_translate("Dialog", "ACAP"))
        self.comboBox_11.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_11.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_11.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_11.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_11.setItemText(4, _translate("Dialog", "very high"))
        self.label_14.setText(_translate("Dialog", "AEXP"))
        self.comboBox_12.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_12.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_12.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_12.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_12.setItemText(4, _translate("Dialog", "very high"))
        self.label_15.setText(_translate("Dialog", "PCAP"))
        self.comboBox_13.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_13.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_13.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_13.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_13.setItemText(4, _translate("Dialog", "very high"))
        self.label_16.setText(_translate("Dialog", "VEXP"))
        self.comboBox_14.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_14.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_14.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_14.setItemText(3, _translate("Dialog", "high"))
        self.label_17.setText(_translate("Dialog", "LTEX"))
        self.comboBox_15.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_15.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_15.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_15.setItemText(3, _translate("Dialog", "high"))
        self.label_18.setText(_translate("Dialog", "MODP"))
        self.comboBox_16.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_16.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_16.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_16.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_16.setItemText(4, _translate("Dialog", "very high"))
        self.label_19.setText(_translate("Dialog", "TOOL"))
        self.comboBox_17.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_17.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_17.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_17.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_17.setItemText(4, _translate("Dialog", "very high"))
        self.label_20.setText(_translate("Dialog", "SCED"))
        self.comboBox_18.setItemText(0, _translate("Dialog", "normal"))
        self.comboBox_18.setItemText(1, _translate("Dialog", "very low"))
        self.comboBox_18.setItemText(2, _translate("Dialog", "low"))
        self.comboBox_18.setItemText(3, _translate("Dialog", "high"))
        self.comboBox_18.setItemText(4, _translate("Dialog", "very high"))
        self.radioButton_4.setText(_translate("Dialog", "Assembler"))
        self.radioButton_5.setText(_translate("Dialog", "C"))
        self.radioButton_6.setText(_translate("Dialog", "Fortran 95"))
        self.radioButton_7.setText(_translate("Dialog", "Pascal"))
        self.radioButton_8.setText(_translate("Dialog", "Tcl"))
        self.radioButton_9.setText(_translate("Dialog", "C++"))
        self.radioButton_10.setText(_translate("Dialog", "Java"))
        self.radioButton_11.setText(_translate("Dialog", "Haskell"))
        self.radioButton_12.setText(_translate("Dialog", "Visual Basic 5"))
        self.radioButton_13.setText(_translate("Dialog", "Smalltalk"))
        self.radioButton_14.setText(_translate("Dialog", "SQL"))
        self.label_7.setText(_translate("Dialog", "Precision"))

    def showokmessage(self):
        okdialog = QtWidgets.QMessageBox()
        okdialog.setText("Click on calculate! NOT OK! -.-")
        okdialog.setWindowTitle("Info")
        okdialog.exec_()

    def calclicked(self):
        ptype = self.buttonGroup.checkedButton().text()
        ufp = self.spinBox.value()
        sellang = self.buttonGrouplang.checkedButton().text()
        kloc = self.spinBox_2.value()
        precision = self.spinBox_3.value()
        selmod = {
            "RELY": self.comboBox.currentText(),
            "DATA": self.comboBox_2.currentText(),
            "CPLX": self.comboBox_6.currentText(),
            "TIME": self.comboBox_7.currentText(),
            "STOR": self.comboBox_8.currentText(),
            "VIRT": self.comboBox_9.currentText(),
            "TURN": self.comboBox_10.currentText(),
            "ACAP": self.comboBox_11.currentText(),
            "AEXP": self.comboBox_12.currentText(),
            "PCAP": self.comboBox_13.currentText(),
            "VEXP": self.comboBox_14.currentText(),
            "LTEX": self.comboBox_15.currentText(),
            "MODP": self.comboBox_16.currentText(),
            "TOOL": self.comboBox_17.currentText(),
            "SCED": self.comboBox_18.currentText(),
        }

        if self.spinBox_2.isEnabled():
            math = CocomoMath(ptype, ufp, sellang, selmod, precision, kloc=kloc)
        else:
            math = CocomoMath(ptype, ufp, sellang, selmod, precision)

        if self.radioButton_4.isEnabled():
            math2str = "==== COCOMO Calculator ==== \n\n" \
                       "==Formulas== \n" \
                       "KDLOC: (UFP * languagevalue) / 1000 \n" \
                       "MOD: RELY * DATA * CPLX * TIME * STOR * VIRT...\n" \
                       "PM: alpha * KDLOC^beta * MOD\n" \
                       "T_DEV: 2.5 * PM^gamma\n" \
                       "TG: PM / T_DEV\n\n" \
                       "==Formulas with inserted values==\n" \
                       "MOD: {} \n" \
                       "KDLOC: {} \n" \
                       "PM: {} \n" \
                       "T_DEV: {} \n" \
                       "TG: {} \n" \
                       "Langvalues: ALPHA: {}, BETA: {}, GAMMA: {}\n\n" \
                       "==YOUR VALUES==\n" \
                       "KDLOC: {} \n" \
                       "MOD: {} \n" \
                       "PM: {} \n" \
                       "T_DEV: {} \n" \
                       "TG: {}".format(math.getmodformula(), math.getkdlocformula(), math.getpmformula(),
                                       math.gettdevformula(), math.gettgformula(), math.getalpha(), math.getbeta(),
                                       math.getgamma(), math.getkdloc(), math.getmod(), math.getpm(), math.gettdev(),
                                       math.gettg())
        else:
            math2str = "==== COCOMO Calculator ==== \n\n" \
                       "==Formulas== \n" \
                       "KDLOC: (UFP * languagevalue) / 1000 \n" \
                       "MOD: RELY * DATA * CPLX * TIME * STOR * VIRT...\n" \
                       "PM: alpha * KDLOC^beta * MOD\n" \
                       "T_DEV: 2.5 * PM^gamma\n" \
                       "TG: PM / T_DEV\n\n" \
                       "==Formulas with inserted values==\n" \
                       "MOD: {} \n" \
                       "PM: {} \n" \
                       "T_DEV: {} \n" \
                       "TG: {} \n\n" \
                       "==YOUR VALUES==\n" \
                       "KDLOC: {} \n" \
                       "MOD: {} \n" \
                       "PM: {} \n" \
                       "T_DEV: {} \n" \
                       "TG: {}".format(math.getmodformula(), math.getpmformula(),
                                       math.gettdevformula(), math.gettgformula(), math.getkdloc(), math.getmod(), math.getpm(), math.gettdev(),
                                       math.gettg())

        self.textEdit.setText(math2str)

    def deackloc(self):
        if self.spinBox.value() > 0:
            self.spinBox_2.setEnabled(False)
            self.pushButton.setEnabled(True)
        else:
            self.spinBox_2.setEnabled(True)
            self.pushButton.setEnabled(False)

    def deacufp(self):
        if self.spinBox_2.value() > 0:
            self.pushButton.setEnabled(True)
            self.spinBox.setEnabled(False)
            self.radioButton_4.setEnabled(False)
            self.radioButton_5.setEnabled(False)
            self.radioButton_6.setEnabled(False)
            self.radioButton_7.setEnabled(False)
            self.radioButton_8.setEnabled(False)
            self.radioButton_9.setEnabled(False)
            self.radioButton_10.setEnabled(False)
            self.radioButton_11.setEnabled(False)
            self.radioButton_12.setEnabled(False)
            self.radioButton_13.setEnabled(False)
            self.radioButton_14.setEnabled(False)
        else:
            self.pushButton.setEnabled(False)
            self.spinBox.setEnabled(True)
            self.radioButton_4.setEnabled(True)
            self.radioButton_5.setEnabled(True)
            self.radioButton_6.setEnabled(True)
            self.radioButton_7.setEnabled(True)
            self.radioButton_8.setEnabled(True)
            self.radioButton_9.setEnabled(True)
            self.radioButton_10.setEnabled(True)
            self.radioButton_11.setEnabled(True)
            self.radioButton_12.setEnabled(True)
            self.radioButton_13.setEnabled(True)
            self.radioButton_14.setEnabled(True)
